### PR TITLE
Use builtin WebView

### LINKED ISSUE #1: Verify works on android
update https://github.com/facebook/react-native/issues/1424 when finished

### LINKED ISSUE #7: Use new webview API for react native

### LINKED ISSUE #8: Solving the getRandomValues problem
One thing that I would like to change asap is that `getRandomValues` currently doesn't fill the buffer immediately. I can see why the current approach was done, but I think that it's a security bug waiting to happen.

Some alternatives as I see them:

1) Build a native module that exports an initial seed derived from a secure RNG, then use that seed in a JavaScript implemented RNG that we call when `getRandomValues` is called. If done correctly, this should keep the properties of the underlying secure RNG.

2) Keep a pool of random data that asynchronously fills by polling the webview for more data. If `getRandomValue` is called when there isn't enough random data, throw an error.

3) Add `getRandomValues` directly into React Native as a pull request.

I would love to see option 3 here, but realistically I think that option 2 is the easiest to implement short term. Option 1 would require very much scrutiny and tests to make sure that our RNG maintains the security properties of the underlying. Basically, we would need to check which RNG e.g. Android uses and implement the same one in JavaScript.

I think I'll try to take a stab at option 2, since it should be a quick fix.

### PR DESCRIPTION
**Pull request by LinusU**
Not quite ready yet, need to test it a bit more. Seems like Android <0.57 still have some problems with this, possible the messages sent over postMessage that aren't escaped properly. Might be worth it to just require 0.57 instead of trying to work around it...

when done, it fixes #1, fixes #7, fixes #8

### CODE REVIEW

**Comment by saulshanabrook** [comment]
Sorry @LinusU I totally missed this! If you are still interested, I would be happy to make you a contributor of this repo and let you publish as you see fit.

**Comment by sirpy** [comment]
@saulshanabrook 
@LinusU What's the status on this? did you get it working?
i've tried to mess around with it, replaced webview with react-native-webview
messaging works good.
once I tried to generate a key, it then enters into an importkey loop. for some reason I saw that the serializebinary that parses the result from webview calls importkey

**Comment by saulshanabrook** [comment]
@sirpy I don't have time to work on this project at the moment. If you want to help maintain it, I am happy to support you though!

**Comment by sirpy** [comment]
> @sirpy I don't have time to work on this project at the moment. If you want to help maintain it, I am happy to support you though!
@saulshanabrook @LinusU 
sure i'll be happy to make a PR, if you can explain what i've asked about serializebinary/importkey

**Comment by sirpy** [comment]
main branch contains a working version based on this work.

**Pull request closed without merging**
